# Generated by Django 5.1.2 on 2024-11-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_buyer_balance_alter_game_cost_alter_game_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=37)),
                ('branch', models.CharField(max_length=20)),
                ('transfer', models.TextField(default='')),
                ('visiter', models.ManyToManyField(related_name='stations', to='task1.buyer')),
            ],
        ),
    ]
