# Generated by Django 5.1.2 on 2024-11-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.CharField(default='saint-petersburg', max_length=16),
        ),
    ]
